name: Deploy to Arvan Object Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install s3cmd
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd


      - name: Configure s3cmd
        run: |
          cat > ~/.s3cfg <<CONFIG
          [default]
          access_key = ${{ secrets.ARVAN_ACCESS_KEY }}
          secret_key = ${{ secrets.ARVAN_SECRET_KEY }}
          host_base = s3.ir-thr-at1.arvanstorage.ir
          host_bucket = %(bucket)s.s3.ir-thr-at1.arvanstorage.ir
          use_https = True
          bucket_location = ir-thr-at1
          signature_v2 = False
          CONFIG

      - name: Deploy website
        run: |
          s3cmd sync ./ s3://houseoftechnocrats/ \
            --delete-removed \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".DS_Store"
